# Distribuições Discretas

## Bernoulli

##### Uma tentativa com dois resultados possíveis: sucesso (1) ou fracasso (0).

In [6]:
from scipy.stats import bernoulli
import numpy as np

In [7]:
p = 0.3  # probabilidade de sucesso

# Gerar 10 amostras
samples = bernoulli.rvs(p, size=10)
print("Amostras:", samples)

# PMF (função massa de probabilidade)
print("P(X=1):", bernoulli.pmf(1, p))
print("P(X=0):", bernoulli.pmf(0, p))

# Esperança e variância
print("Média:", bernoulli.mean(p))
print("Variância:", bernoulli.var(p))

Amostras: [0 0 0 0 0 0 0 0 1 1]
P(X=1): 0.3
P(X=0): 0.7000000000000002
Média: 0.3
Variância: 0.21


## Binomial

##### Conta o número de sucessos em n tentativas independentes.

In [ ]:
from scipy.stats import binom

n, p = 10, 0.5  # 10 tentativas, p = 0.5

# PMF: probabilidade de exatamente 4 sucessos
print("P(X=4):", binom.pmf(4, n, p))

# CDF: probabilidade de até 4 sucessos
print("P(X<=4):", binom.cdf(4, n, p))

# Amostragem
samples = binom.rvs(n, p, size=10)
print("Amostras:", samples)

# Média e variância
print("Média:", binom.mean(n, p))
print("Variância:", binom.var(n, p))


## Geométrica

##### Conta o número de falhas antes do primeiro sucesso.

In [10]:
from scipy.stats import geom

p = 0.2

# PMF: probabilidade de primeira ocorrência de sucesso após 4 tentativas
print("P(X=4):", geom.pmf(4, p))  # 3 falhas + 1 sucesso

# Média e variância
print("Média:", geom.mean(p))
print("Variância:", geom.var(p))


P(X=4): 0.10240000000000003
Média: 5.0
Variância: 20.0


## HyperGeométrica

##### Amostragem sem reposição.

In [9]:
from scipy.stats import hypergeom

# N = população, K = sucesso na população, n = tamanho da amostra
N, K, n = 100, 70, 7

# Probabilidade de exatamente 3 sucessos
print("P(X=3):", hypergeom.pmf(3, N, K, n))

# Média e variância
print("Média:", hypergeom.mean(N, K, n))
print("Variância:", hypergeom.var(N, K, n))


P(X=3): 0.09371507119310772
Média: 4.9
Variância: 1.3809090909090909


## Poisson

##### Modela o número de eventos por unidade de tempo/área.

In [11]:
from scipy.stats import poisson

λ = 3  # taxa média

# PMF: probabilidade de exatamente 2 eventos
print("P(X=2):", poisson.pmf(2, λ))

# Média e variância
print("Média:", poisson.mean(λ))
print("Variância:", poisson.var(λ))


P(X=2): 0.22404180765538775
Média: 3.0
Variância: 3.0


## Distribuição Binomial Negativa

##### Conta o número de falhas antes de alcançar r sucessos.

In [31]:
from scipy.stats import nbinom

r = 4       # número de sucessos desejados
p = 0.2     # probabilidade de sucesso em cada tentativa

# PMF: probabilidade de ocorrerem 11 falhas antes do 4º sucesso (ou seja, 15 tentativas no total)
x = 11  # número de falhas
print("P(X=11 falhas):", nbinom.pmf(x, r, p))

# Geração de amostras
samples = nbinom.rvs(r, p, size=10)
print("Amostras (falhas até o 4º sucesso):", samples)

# Esperança e variância
print("Média:", nbinom.mean(r, p))
print("Variância:", nbinom.var(r, p))


P(X=11 falhas): 0.05002777906380801
Amostras (falhas até o 4º sucesso): [16 24  3 16 23 10  6 29  8 10]
Média: 16.0
Variância: 79.99999999999999


## Multinomial

##### Geralização da binomial para mais de dois possíveis resultados por ensaio.

In [30]:
from scipy.stats import multinomial
import numpy as np

n = 12  # número total de experimentos
p = [1/6]*6  # probabilidade para cada face de um dado

# PMF: probabilidade de cada face sair exatamente 2 vezes
x = [2]*6  # 2 vezes cada face
prob = multinomial.pmf(x, n=n, p=p)
print("P(x=2 para cada face):", prob)

# Amostras aleatórias
samples = multinomial.rvs(n=n, p=p, size=5)
print("Amostras:\n", samples)


P(x=2 para cada face): 0.003438285893918611
Amostras:
 [[2 1 1 3 2 3]
 [3 2 2 2 3 0]
 [3 1 1 2 5 0]
 [4 5 0 2 1 0]
 [3 4 2 2 0 1]]


# Distribuições Contínuas

## Uniforme

##### Todos os valores dentro de um intervalo têm a mesma probabilidade.

In [14]:
from scipy.stats import uniform

a, b = 0, 10  # intervalo [a, a + b]

# PDF: densidade de probabilidade em x = 5
print("f(5):", uniform.pdf(5, loc=a, scale=b))

# CDF: probabilidade acumulada até x = 5
print("F(5):", uniform.cdf(5, loc=a, scale=b))

# Geração de amostras
samples = uniform.rvs(loc=a, scale=b, size=1000)

# Média e variância
print("Média:", uniform.mean(loc=a, scale=b))
print("Variância:", uniform.var(loc=a, scale=b))


f(5): 0.1
F(5): 0.5
Média: 5.0
Variância: 8.333333333333332


## Normal

##### A famosa “curva em sino”.

In [17]:
from scipy.stats import norm

mu, sigma = 0, 1  # média e desvio padrão

# PDF e CDF em x = 1
print("f(1):", norm.pdf(1, loc=mu, scale=sigma))
print("F(1):", norm.cdf(1, loc=mu, scale=sigma))

# Amostras aleatórias
samples = norm.rvs(loc=mu, scale=sigma, size=1000)

# Média e variância
print("Média:", norm.mean(loc=mu, scale=sigma))
print("Variância:", norm.var(loc=mu, scale=sigma))


f(1): 0.24197072451914337
F(1): 0.8413447460685429
Média: 0.0
Variância: 1.0


## Exponencial

##### Modela o tempo até um evento ocorrer.

In [16]:
from scipy.stats import expon

λ = 2  # taxa = 1/escala
scale = 1 / λ

# PDF e CDF em x = 1
print("f(1):", expon.pdf(1, scale=scale))
print("F(1):", expon.cdf(1, scale=scale))

# Amostras
samples = expon.rvs(scale=scale, size=1000)

# Média e variância
print("Média:", expon.mean(scale=scale))
print("Variância:", expon.var(scale=scale))


f(1): 0.2706705664732254
F(1): 0.8646647167633873
Média: 0.5
Variância: 0.25


# Exercícios

In [12]:
λ = 20  # taxa média

In [13]:
poisson.pmf(25,λ)

0.04458764910826764

## Exercício normal

In [20]:
mu, sigma = 70, 5  # média e desvio padrão

norm.cdf(85, loc=mu, scale=sigma)

### Exercício 2

O faturamento diário de um motorista de aplicativo segue uma distribuição aproximadamente normal, com média R$ 300,00 e desvio padrão igual a R$ 50,00. Obtenha as probabilidades de que, em um dia aleatório, o motorista ganhe:

1) Entre R$ 250,00 e R$ 350,00

2) Entre R$ 400,00 e R$ 500,00


In [27]:
mu, sigma = 300, 50  # média e desvio padrão

lowp = norm.cdf(250, loc=mu, scale=sigma)
higp = norm.cdf(350, loc=mu, scale=sigma)

In [29]:
higp-lowp

0.6826894921370859

### Exercício 3

O Inmetro verificou que as lâmpadas incandescentes da fabricante XPTO apresentam uma vida útil normalmente distribuída, com média igual a 720 dias e desvio padrão igual a 30 dias. Calcule a probabilidade de uma lâmpada, escolhida ao acaso, durar:

1) Entre 650 e 750 dias

2) Mais que 800 dias

3) Menos que 700 dias

In [32]:
mu, sigma = 720, 30  # média e desvio padrão

lowp = norm.cdf(650, loc=mu, scale=sigma)
higp = norm.cdf(750, loc=mu, scale=sigma)

A

In [33]:
higp-lowp

0.8315294174398976

B

In [34]:
norm.sf(800, loc=mu, scale=sigma)

0.0038303805675897365

C

In [35]:
norm.cdf(700, loc=mu, scale=sigma)

0.2524925375469229

### Exercício 4

Utilizando a tabela padronizada, ou o ferramental disponibilizado pelo Python, encontre a área sob a curva normal para os valores de Z abaixo:

1) Z < 1,96

2) Z > 2,15

3) Z < -0,78

4) Z > 0,59


NEsse caso como são valores normalizados podemos simplesmente usar o norm sem nenhum parâmetro, pois ele assumirá o valor da normal padronizada

In [37]:
norm.sf(1.96)

0.024997895148220435

In [39]:
norm.sf(2.15)

0.0157776073910905

In [41]:
norm.cdf(-0.78)

0.21769543758573312

In [42]:
norm.sf(0.59)

0.27759532475346493